# Generated by Django 2.2.15 on 2020-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_usersapartaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersapartaments',
            name='is_interesting',
            field=models.BooleanField(default=False),
        ),
    ]
