# Generated by Django 2.2.15 on 2020-08-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_usersapartaments_is_interesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartament',
            name='apartament_id',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='usersapartaments',
            name='apartament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Apartament', to_field='apartament_id'),
        ),
    ]
